<a href="https://colab.research.google.com/github/peemoshi/ai-ml-internship/blob/main/week-1/1.3-math-for-ml/math_for_ml_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

**Section A: Statistics**

Given these 8 quiz scores: ***[62, 75, 80, 80, 90, 55, 70, 85]***

1.   Calculate the mean and variance by hand.
2.   Calculate the standard deviation by hand.
3.   One student scored 95 on a different quiz where the class mean was 78 and std dev was 8.
Calculate their z-score and explain what it means in one sentence.

In [10]:
scores = np.array([62, 75, 80, 80, 90, 55, 70, 85])
print("Mean:", np.mean(scores))
print("Variance:", np.var(scores))
print("Std dev:", np.std(scores))

student_score = 95
class_mean = 78
class_std_dev = 8

z_score = (student_score - class_mean) / class_std_dev
print(f"The z-score for the student is: {z_score:.2f}")

Mean: 74.625
Variance: 120.984375
Std dev: 10.999289749797484
The z-score for the student is: 2.12


**Section B: Probability**

4.   A class has 30 students: 18 study AI, 10
study EdTech, and 2 study both. If a student is picked at random, what's the probability they study **AI OR EdTech**?
5.   **Bayes' rule:** 5% of students have a certain learning difficulty. A screening test correctly flags 90% of students who have it, but also incorrectly flags 10% of students who don't. If a random student tests positive, what's the probability they actually have the difficulty?

### Question 4: Probability of AI OR EdTech

**Problem:** A class has 30 students: 18 study AI, 10 study EdTech, and 2 study both. If a student is picked at random, what's the probability they study **AI OR EdTech**?

**Solution:**
Let A = student studies AI, E = student studies EdTech.
Given:
*   P(A) = 18/30
*   P(E) = 10/30
*   P(A and E) = 2/30

Using the Principle of Inclusion-Exclusion:
P(A or E) = P(A) + P(E) - P(A and E)
P(A or E) = (18/30) + (10/30) - (2/30)
P(A or E) = 28/30 - 2/30 = 26/30 ≈ 0.87

The probability that a student studies AI OR EdTech is approximately **0.87** (or 87%).

### Question 5: Bayes' Rule

**Problem:** 5% of students have a certain learning difficulty. A screening test correctly flags 90% of students who have it, but also incorrectly flags 10% of students who don't. If a random student tests positive, what's the probability they actually have the difficulty?

**Solution:**
Let D = student has difficulty, T = student tests positive.
Given:
*   P(D) = 0.05
*   P(~D) = 1 - 0.05 = 0.95
*   P(T|D) = 0.90
*   P(T|~D) = 0.10

First, calculate the overall probability of testing positive, P(T):
P(T) = P(T|D) * P(D) + P(T|~D) * P(~D)
P(T) = (0.90 * 0.05) + (0.10 * 0.95)
P(T) = 0.045 + 0.095 = 0.14

Now, apply Bayes' Rule: P(D|T) = [P(T|D) * P(D)] / P(T)
P(D|T) = (0.90 * 0.05) / 0.14
P(D|T) = 0.045 / 0.14 ≈ 0.3214

The probability that a student actually has the difficulty given a positive test is approximately **0.32** (or 32%).

### Question 4: Probability of AI OR EdTech

In [11]:
# Given data
total_students = 30
ai_students = 18
edtech_students = 10
both_students = 2

# Calculate probabilities
p_ai = ai_students / total_students
p_edtech = edtech_students / total_students
p_both = both_students / total_students

# Probability of AI OR EdTech using the principle of inclusion-exclusion
p_ai_or_edtech = p_ai + p_edtech - p_both

print(f"Probability of studying AI: {p_ai:.2f}")
print(f"Probability of studying EdTech: {p_edtech:.2f}")
print(f"Probability of studying both: {p_both:.2f}")
print(f"Probability of studying AI OR EdTech: {p_ai_or_edtech:.2f}")

Probability of studying AI: 0.60
Probability of studying EdTech: 0.33
Probability of studying both: 0.07
Probability of studying AI OR EdTech: 0.87


To find the probability that a student studies AI OR EdTech, we use the formula for the union of two events: P(A or B) = P(A) + P(B) - P(A and B).

*   P(AI) = 18/30
*   P(EdTech) = 10/30
*   P(AI and EdTech) = 2/30

So, P(AI or EdTech) = (18/30) + (10/30) - (2/30) = 26/30 = 0.87.

### Question 5: Bayes' Rule

In [12]:
# Given probabilities
p_difficulty = 0.05  # P(D): Probability of having difficulty
p_no_difficulty = 1 - p_difficulty # P(not D)

p_positive_given_difficulty = 0.90  # P(T | D): Test flags positive given difficulty
p_positive_given_no_difficulty = 0.10 # P(T | not D): Test flags positive given no difficulty

# Calculate P(T): Probability of testing positive
# P(T) = P(T | D) * P(D) + P(T | not D) * P(not D)
p_positive = (p_positive_given_difficulty * p_difficulty) + \
             (p_positive_given_no_difficulty * p_no_difficulty)

# Calculate P(D | T) using Bayes' Rule
# P(D | T) = [P(T | D) * P(D)] / P(T)
p_difficulty_given_positive = (p_positive_given_difficulty * p_difficulty) / p_positive

print(f"Probability of having difficulty: {p_difficulty:.2f}")
print(f"Probability of not having difficulty: {p_no_difficulty:.2f}")
print(f"Probability of positive test given difficulty: {p_positive_given_difficulty:.2f}")
print(f"Probability of positive test given no difficulty: {p_positive_given_no_difficulty:.2f}")
print(f"Probability of testing positive: {p_positive:.3f}")
print(f"Probability of actually having the difficulty given a positive test: {p_difficulty_given_positive:.2f}")

Probability of having difficulty: 0.05
Probability of not having difficulty: 0.95
Probability of positive test given difficulty: 0.90
Probability of positive test given no difficulty: 0.10
Probability of testing positive: 0.140
Probability of actually having the difficulty given a positive test: 0.32


This problem requires Bayes' rule. Let 'D' be the event that a student has the learning difficulty and 'T' be the event that a student tests positive.

We are given:
*   P(D) = 0.05 (Prior probability of having the difficulty)
*   P(not D) = 1 - 0.05 = 0.95
*   P(T | D) = 0.90 (Probability of testing positive given they have the difficulty)
*   P(T | not D) = 0.10 (Probability of testing positive given they do not have the difficulty)

We want to find P(D | T), the probability they actually have the difficulty given a positive test.

First, we calculate the overall probability of testing positive, P(T):
P(T) = P(T | D) * P(D) + P(T | not D) * P(not D)
P(T) = (0.90 * 0.05) + (0.10 * 0.95) = 0.045 + 0.095 = 0.14

Now, apply Bayes' Rule:
P(D | T) = [P(T | D) * P(D)] / P(T)
P(D | T) = (0.90 * 0.05) / 0.14 = 0.045 / 0.14 ≈ 0.32

So, even with a positive test, the probability that the student actually has the difficulty is approximately 32%.

**Section C:**

Linear Algebra
Given vectors a = [2, 3, 1] and b = [1, 0, 4], calculate the dot product.
Given matrices A = [[1,2],[3,4]] and B = [[5,6],[7,8]], calculate A @ B (matrix multiplication), showing each entry's calculation.
In one sentence: how does a dot product relate to what a single neuron computes in a neural network?

### Dot Product Calculation

In [13]:
a = np.array([2, 3, 1])
b = np.array([1, 0, 4])

dot_product = np.dot(a, b)

print(f"Vector a: {a}")
print(f"Vector b: {b}")
print(f"Dot product of a and b: {dot_product}")

Vector a: [2 3 1]
Vector b: [1 0 4]
Dot product of a and b: 6


The dot product of two vectors `a = [a1, a2, ..., an]` and `b = [b1, b2, ..., bn]` is calculated as `a1*b1 + a2*b2 + ... + an*bn`.

For `a = [2, 3, 1]` and `b = [1, 0, 4]`:
Dot Product = (2 * 1) + (3 * 0) + (1 * 4) = 2 + 0 + 4 = **6**

### Matrix Multiplication (A @ B)

In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Calculate matrix multiplication
C = np.dot(A, B)

print(f"Matrix A:\n{A}")
print(f"Matrix B:\n{B}")
print(f"Matrix A @ B:\n{C}")

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Matrix A @ B:
[[19 22]
 [43 50]]


For matrix multiplication `C = A @ B`, where `A = [[1,2],[3,4]]` and `B = [[5,6],[7,8]]`:

Each entry `C_ij` is the dot product of the i-th row of A and the j-th column of B.

*   `C_11` (first row, first column) = (1 * 5) + (2 * 7) = 5 + 14 = **19**
*   `C_12` (first row, second column) = (1 * 6) + (2 * 8) = 6 + 16 = **22**
*   `C_21` (second row, first column) = (3 * 5) + (4 * 7) = 15 + 28 = **43**
*   `C_22` (second row, second column) = (3 * 6) + (4 * 8) = 18 + 32 = **50**

Resulting matrix C:
```
[[19, 22],
 [43, 50]]
```

### Dot Product and Neural Networks

A single neuron in a neural network computes a weighted sum of its inputs (a dot product), applies an activation function, and produces an output.

**Section D:**

Calculus / Gradient Descent
Given f(x) = x² + 4x + 3, find the derivative f'(x) by hand.
If we're doing gradient descent on this function starting at x = 5 with a learning rate of 0.1, calculate one update step: x_new = x - learning_rate * f'(x).
In 2–3 sentences: explain what the gradient tells you and why we subtract it (not add it) when updating parameters.

### Derivative and Gradient Descent

**1. Derivative of f(x) = x² + 4x + 3:**
Using the power rule and sum rule for derivatives:
`f'(x) = d/dx(x²) + d/dx(4x) + d/dx(3)`
`f'(x) = 2x + 4 + 0`
`f'(x) = 2x + 4`

In [16]:
# Given initial values
x = 5
learning_rate = 0.1

# Calculate the derivative f'(x) = 2x + 4
f_prime_x = 2 * x + 4

# Calculate one update step: x_new = x - learning_rate * f'(x)
x_new = x - learning_rate * f_prime_x

print(f"Initial x: {x}")
print(f"Derivative f'(x) at x={x}: {f_prime_x}")
print(f"Learning rate: {learning_rate}")
print(f"New x after one update step: {x_new}")

Initial x: 5
Derivative f'(x) at x=5: 14
Learning rate: 0.1
New x after one update step: 3.5999999999999996


The gradient (derivative) tells us the direction and steepness of the function's slope at a given point. We subtract the gradient (multiplied by the learning rate) when updating parameters in gradient descent because we want to move in the direction opposite to the steepest ascent to find the minimum of the function.